# Generated by Django 3.1.7 on 2021-07-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('MTW', 'Mens Top Wear'), ('WTW', 'Womens Top Wear'), ('MBW', 'Mens Bottom Wear'), ('WBW', 'Womens Bottom Wear'), ('KW', 'Kids Wear')], max_length=3),
        ),
    ]
